version: 1.2
workflows:

  # combined
  - name: optimus_dropulation
    subclass: WDL
    primaryDescriptorPath: /combined/optimus_dropulation/optimus_dropulation.wdl
  - name: optimus_cbrb
    subclass: WDL
    primaryDescriptorPath: /combined/optimus_cbrb/optimus_cbrb.wdl
  - name: selection_dropulation
    subclass: WDL
    primaryDescriptorPath: /combined/selection_dropulation/selection_dropulation.wdl

  # pipelines
  - name: cell_classification
    subclass: WDL
    primaryDescriptorPath: /pipelines/cell_classification/cell_classification.wdl
  - name: cell_selection
    subclass: WDL
    primaryDescriptorPath: /pipelines/cell_selection/cell_selection.wdl
  - name: dropseq_cbrb
    subclass: WDL
    primaryDescriptorPath: /pipelines/dropseq_cbrb/dropseq_cbrb.wdl
  - name: optimus_post_processing
    subclass: WDL
    primaryDescriptorPath: /pipelines/optimus_post_processing/optimus_post_processing.wdl
  - name: standard_analysis
    subclass: WDL
    primaryDescriptorPath: /pipelines/standard_analysis/standard_analysis.wdl
  - name: tensorqtl
    subclass: WDL
    primaryDescriptorPath: /pipelines/tensorqtl/tensorqtl.wdl
